// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DailyBlockRecord = { discord_id: string, block: number, amount: number, created_at: bigint, };
