// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockThreshold } from "./BlockThreshold";
import type { DistanceThreshold } from "./DistanceThreshold";

export type Threshold = { "DISTANCE": DistanceThreshold } | { "BLOCK": BlockThreshold };
